name: checkwps
on: [push]
jobs:
  checkwps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Deploy Script
      working-directory: ${{ github.workspace }}/PROJECT_FOLDER
      run: bash ./publish-script.sh