name: checkwps
on: [push]
jobs:
  checkwps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./checkwps ../Themify_2/.rockbox/wps/Themify_2.sbs ../Themify_2/.rockbox/wps/Themify_2.wps
